export type Lang = "en" | "ru";

export const company = {
  legalName: "UNIQ TRADE INCORPORATED",
  shortName: "UNIQ TRADE INC.",
  phoneDisplay: "+1 301 092 13136",
  phoneHref: "+130109213136",
  email: "uniq_trade@californiamail.com",
  address: ["1089 Stratford CT", "Loveland, OH 45140", "United States"],
};

export const images = {
  hero: "https://images.pexels.com/photos/31257317/pexels-photo-31257317.jpeg?auto=compress&cs=tinysrgb&w=2200",
  compressor: "https://images.pexels.com/photos/31257317/pexels-photo-31257317.jpeg?auto=compress&cs=tinysrgb&w=1600",
  pump: "https://images.pexels.com/photos/35645884/pexels-photo-35645884.jpeg?auto=compress&cs=tinysrgb&w=1600",
  machinery: "https://images.pexels.com/photos/5953729/pexels-photo-5953729.jpeg?auto=compress&cs=tinysrgb&w=1600",
  refinery: "https://images.pexels.com/photos/15970032/pexels-photo-15970032.jpeg?auto=compress&cs=tinysrgb&w=1800",
  mining: "https://images.pexels.com/photos/6109677/pexels-photo-6109677.jpeg?auto=compress&cs=tinysrgb&w=1800",
  plant: "https://images.pexels.com/photos/4440200/pexels-photo-4440200.jpeg?auto=compress&cs=tinysrgb&w=1600",
};

export const content = {
  en: {
    nav: [
      ["Products", "/products"],
      ["Industries", "/industries"],
      ["About Us", "/about"],
      ["Why Us", "/why-uniq"],
      ["How We Work", "/how-we-work"],
    ],
    hero: {
      eyebrow: "INDUSTRIAL PROCUREMENT & SUPPLY",
      titleA: "Industrial Spare Parts",
      titleB: "& Equipment Supply",
      text: "Sourcing and supply of spare parts and components for industrial equipment across oil & gas, chemical, mining, metallurgical and other industrial sectors.",
      primary: "Request a Quote",
      secondary: "Explore Products",
      proof: ["Compressors", "Pumps", "Engines & Motors", "Valves & Components"],
    },
    home: {
      introEyebrow: "UNIQ TRADE INC.",
      introTitle: "The right part. The right source. The right delivery.",
      introText: "UNIQ TRADE INCORPORATED is a U.S.-based trading company focused on sourcing and supplying spare parts and components for demanding industrial applications.",
      productsTitle: "What We Supply",
      productsText: "A focused portfolio for the equipment that keeps industrial facilities operating.",
      industriesTitle: "Industries We Serve",
      industriesText: "Our supply capabilities support critical equipment used across major industrial sectors.",
      whyTitle: "Why UNIQ TRADE",
      whyText: "International sourcing, practical technical understanding and coordinated procurement support.",
      processTitle: "How We Work",
      processText: "A clear process from your first request to coordinated delivery.",
      ctaTitle: "Have a specific spare part to source?",
      ctaText: "Send the equipment model, manufacturer, part number, drawing or technical specification. We will review the requirement.",
    },
    products: [
      ["Compressors", "Components and spare parts for reciprocating, screw and centrifugal compressor systems: valves, rings, gaskets and related items.", images.compressor],
      ["Pumps", "Components and spare parts for centrifugal, process and industrial pumping equipment, including seals, impellers and bearings.", images.pump],
      ["Engines & Motors", "Replacement and mechanical components for industrial engines, electric motors and motor-driven equipment.", images.machinery],
      ["Valves & Piping Components", "Industrial valves, fittings, seals and related piping components for process and utility systems.", images.plant],
      ["Mechanical Components", "Bearings, seals, gaskets, couplings, shafts and other parts for industrial equipment maintenance.", images.machinery],
      ["Electrical & Instrumentation", "Electrical, control and instrumentation components for industrial equipment and process applications.", images.plant],
    ],
    industries: [
      ["Oil & Gas", "Spare parts and components for production, processing, transportation and related facilities.", images.refinery],
      ["Chemical", "Supply support for process equipment, production facilities and chemical plants.", images.plant],
      ["Mining & Metallurgy", "Components for heavy machinery, processing equipment and metallurgical operations.", images.mining],
      ["Industrial & Power", "Procurement support for industrial plants, utilities and power-related equipment.", images.machinery],
    ],
    about: {
      eyebrow: "ABOUT UNIQ TRADE",
      title: "Industrial supply with a practical approach.",
      paragraphs: [
        "UNIQ TRADE INCORPORATED is a U.S.-based trading company specializing in the sourcing and supply of spare parts and components for industrial equipment.",
        "We support customers operating in oil & gas, chemical, mining, metallurgical and other industrial sectors, helping them identify and procure required components for compressors, pumps, engines, motors and other critical equipment.",
        "Our focus is simple: understand the requirement, identify a suitable source, coordinate procurement and support delivery to the customer's specification.",
      ],
    },
    why: [
      ["01", "Global Sourcing", "Access to international suppliers and manufacturers for hard-to-find industrial components."],
      ["02", "Technical Understanding", "We work with equipment models, part numbers, specifications and application requirements."],
      ["03", "Industrial Focus", "Our activities are centered on industrial equipment and the spare parts that keep operations moving."],
      ["04", "Procurement Support", "We coordinate sourcing, quotations and purchasing requirements around the customer's request."],
      ["05", "Quality Focus", "Requirements and supplied components are reviewed against available technical and commercial information."],
      ["06", "Delivery Coordination", "We support the process from sourcing through shipment and delivery coordination."],
    ],
    process: [
      ["01", "Request", "Send an equipment model, OEM part number, drawing, specification or description of the required part."],
      ["02", "Technical Review", "We review the requirement and clarify the key technical and commercial parameters."],
      ["03", "Sourcing", "We identify suitable manufacturers, suppliers or sourcing channels."],
      ["04", "Verification", "Available specifications, origin and commercial details are reviewed before quotation."],
      ["05", "Quotation", "We provide the available commercial proposal and delivery information."],
      ["06", "Delivery", "After confirmation, procurement and delivery are coordinated according to the agreed terms."],
    ],
    contact: {
      eyebrow: "REQUEST A QUOTE",
      title: "Tell us what you need.",
      text: "For a quotation, send us your equipment model, manufacturer, part number, drawing or technical specification.",
      form: ["Name", "Company", "Email", "Phone", "Equipment / Manufacturer / Part Number", "Quantity", "Message"],
      button: "Send Request",
    },
  },
  ru: {
    nav: [
      ["Продукция", "/ru/products"],
      ["Отрасли", "/ru/industries"],
      ["О компании", "/ru/about"],
      ["Почему мы", "/ru/why-uniq"],
      ["Как работаем", "/ru/how-we-work"],
    ],
    hero: {
      eyebrow: "ПРОМЫШЛЕННЫЕ ЗАПЧАСТИ И СНАБЖЕНИЕ",
      titleA: "Поставка запасных частей",
      titleB: "и промышленного оборудования",
      text: "Поиск и поставка запасных частей и компонентов для промышленного оборудования в нефтегазовой, химической, горно-металлургической и других отраслях.",
      primary: "Запросить предложение",
      secondary: "Посмотреть продукцию",
      proof: ["Компрессоры", "Насосы", "Двигатели", "Арматура и компоненты"],
    },
    home: {
      introEyebrow: "UNIQ TRADE INC.",
      introTitle: "Нужная деталь. Надёжный источник. Организованная поставка.",
      introText: "UNIQ TRADE INCORPORATED — торговая компания из США, специализирующаяся на поиске и поставке запасных частей и компонентов для промышленного оборудования.",
      productsTitle: "Что мы поставляем",
      productsText: "Профильное снабжение оборудования, от которого зависит работа промышленных предприятий.",
      industriesTitle: "Отрасли",
      industriesText: "Наши поставки ориентированы на критически важное оборудование крупных промышленных объектов.",
      whyTitle: "Почему UNIQ TRADE",
      whyText: "Международный поиск, практическое техническое понимание и координация закупки.",
      processTitle: "Как мы работаем",
      processText: "Понятный процесс от первого запроса до координации поставки.",
      ctaTitle: "Ищете конкретную запчасть?",
      ctaText: "Отправьте модель оборудования, производителя, артикул, чертёж или техническую спецификацию — мы рассмотрим запрос.",
    },
    products: [
      ["Компрессоры", "Компоненты и запасные части для поршневых, винтовых и центробежных систем: клапаны, кольца, прокладки и другие позиции.", images.compressor],
      ["Насосы", "Компоненты и запасные части для центробежных, технологических и промышленных насосов: уплотнения, рабочие колёса, подшипники.", images.pump],
      ["Двигатели и электродвигатели", "Сменные и механические компоненты для промышленных двигателей, электродвигателей и приводного оборудования.", images.machinery],
      ["Клапаны и трубопроводные компоненты", "Промышленная арматура, фитинги, уплотнения и компоненты трубопроводных систем.", images.plant],
      ["Механические компоненты", "Подшипники, уплотнения, прокладки, муфты, валы и другие детали для обслуживания промышленного оборудования.", images.machinery],
      ["Электрика и КИПиА", "Электрические, управляющие и измерительные компоненты для промышленного оборудования и технологических процессов.", images.plant],
    ],
    industries: [
      ["Нефтегазовая отрасль", "Запасные части и компоненты для добывающих, перерабатывающих, транспортных и других объектов.", images.refinery],
      ["Химическая промышленность", "Поставки для технологического оборудования, производственных линий и химических предприятий.", images.plant],
      ["Горнодобывающая и металлургическая отрасли", "Компоненты для тяжёлой техники, обогатительного оборудования и металлургических производств.", images.mining],
      ["Промышленность и энергетика", "Закупочная поддержка для промышленных предприятий, инженерных систем и энергетического оборудования.", images.machinery],
    ],
    about: {
      eyebrow: "О КОМПАНИИ",
      title: "Промышленное снабжение с практическим подходом.",
      paragraphs: [
        "UNIQ TRADE INCORPORATED — торговая компания из США, специализирующаяся на поиске и поставке запасных частей и компонентов для промышленного оборудования.",
        "Мы работаем с заказчиками нефтегазовой, химической, горнодобывающей, металлургической и других промышленных отраслей, помогая находить и закупать необходимые компоненты для компрессоров, насосов, двигателей, электродвигателей и другого критически важного оборудования.",
        "Наш подход прост: понять потребность, найти подходящий источник, организовать закупку и поддержать поставку в соответствии с требованиями заказчика.",
      ],
    },
    why: [
      ["01", "Международный поиск", "Работа с международными поставщиками и производителями для поиска необходимых промышленных компонентов."],
      ["02", "Техническое понимание", "Работаем с моделями оборудования, артикулами, спецификациями и требованиями к применению."],
      ["03", "Фокус на промышленности", "Наш профиль — промышленное оборудование и запасные части, необходимые для его эксплуатации."],
      ["04", "Закупочная поддержка", "Координируем поиск, коммерческие предложения и закупочные требования заказчика."],
      ["05", "Контроль требований", "Сопоставляем доступные технические и коммерческие данные с исходным запросом."],
      ["06", "Координация поставки", "Поддерживаем процесс от поиска до отгрузки и координации доставки."],
    ],
    process: [
      ["01", "Запрос", "Вы отправляете модель оборудования, OEM-артикул, чертёж, спецификацию или описание требуемой детали."],
      ["02", "Технический анализ", "Изучаем запрос и уточняем ключевые технические и коммерческие параметры."],
      ["03", "Поиск", "Определяем подходящих производителей, поставщиков и каналы закупки."],
      ["04", "Проверка", "Перед предложением анализируем доступные характеристики, происхождение и коммерческие данные."],
      ["05", "Предложение", "Предоставляем доступное коммерческое предложение и информацию по срокам поставки."],
      ["06", "Поставка", "После подтверждения организуем закупку и координацию доставки на согласованных условиях."],
    ],
    contact: {
      eyebrow: "ЗАПРОС ПРЕДЛОЖЕНИЯ",
      title: "Расскажите, что вам требуется.",
      text: "Для получения предложения отправьте модель оборудования, производителя, артикул, чертёж или техническую спецификацию.",
      form: ["Имя", "Компания", "Email", "Телефон", "Оборудование / Производитель / Артикул", "Количество", "Сообщение"],
      button: "Отправить запрос",
    },
  },
} as const;
